apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-frontend-shell
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcc-frontend-shell
  template:
    metadata:
      labels:
        app: tcc-frontend-shell
    spec:
      containers:
        - name: shell
          image: ahmentz/tcc-frontend:front-shell-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
