apiVersion: v1
kind: Service
metadata:
  name: frontend-catalog-service
  namespace: default
spec:
  selector:
    app: tcc-frontend-catalog
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
