name: Build - MFE Shell

on:
  push:
    branches: [ main ]
    paths:
      - 'projects/frontend-shell/**'
      - 'projects/frontend-lib/**'
      - '.github/workflows/frontend-shell.yml'
      - 'package.json'
      - 'angular.json'
      - 'tsconfig.json'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: false
        default: 'development'
        
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
         
      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
         
      - name: Build Frontend Lib
        run: npm run build frontend-lib
       
      - name: Build MFE
        run: npm run build frontend-shell -- --configuration production
       
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
         
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Copy Dockerfile to root context
        run: cp ./projects/frontend-shell/Dockerfile ./Dockerfile
      
      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ahmentz/tcc-frontend
          flavor: |
            prefix=frontend-shell-
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            latest
           
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=development
