name: Build - MFE Shell

on:
  push:
    branches: [ main ]
    paths:
      - 'projects/frontend-shell/**'
      - 'projects/frontend-lib/**'
      - 'package.json'
      - 'angular.json'
      - 'tsconfig.json'
  workflow_dispatch: # Add this for manual triggers (ignores paths)
    inputs: # Optional: Allow custom inputs when running manually
      environment: # Example input for overrides
        description: 'Environment to build for (e.g., production)'
        required: false
        default: 'production'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
         
      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
         
      - name: Build Frontend Lib
        run: npm run build frontend-lib
       
      - name: Build MFE
        run: npm run build frontend-shell -- --configuration production
       
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request' # Only login on actual pushes
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} # Use a Docker Hub access token for security
         
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Enables cache support
      - name: Debug paths
        run: ls -la ./projects/frontend-shell
       
      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ahmentz/tcc-frontend # e.g., ahmentz/tcc-frontend
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            latest
           
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./projects/frontend-shell  # Change to subdirectory for correct path resolution
          file: Dockerfile  # Relative to new context (no need for full path)
          push: ${{ github.event_name != 'pull_request' }} # Push only on pushes/tags
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max # Cache Docker layers for efficiency
          build-args: | # Optional overrides for build-time (e.g., for Angular env)
            NODE_ENV=production
