- name: Log in to Docker Hub
        if: github.event_name != 'pull_request'  # Only login on actual pushes
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use a Docker Hub access token for security

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Enables cache support

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository_owner }}/tcc-frontend  # e.g., augustomentz/tcc-frontend
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .  # Use root as context (adjust if submodule)
          push: ${{ github.event_name != 'pull_request' }}  # Push only on pushes/tags
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max  # Cache Docker layers for efficiency
          build-args: |  # Optional overrides for build-time (e.g., for Angular env)
            NODE_ENV=production

      - name: Scan image for vulnerabilities (Optional)
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.meta.outputs.tags }}'
          format: 'table'
          exit-code: '1'  # Fail on critical issues
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
